// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mlp.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	mlp.proto

It has these top-level messages:
	MLP
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Activation is a valid activation function
type Activation int32

const (
	Activation_IDENTITY Activation = 0
	Activation_TANH     Activation = 1
	Activation_RELU     Activation = 2
)

var Activation_name = map[int32]string{
	0: "IDENTITY",
	1: "TANH",
	2: "RELU",
}
var Activation_value = map[string]int32{
	"IDENTITY": 0,
	"TANH":     1,
	"RELU":     2,
}

func (x Activation) String() string {
	return proto.EnumName(Activation_name, int32(x))
}
func (Activation) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// MLP contains the weights and specification for a multi-layer perceptron.
type MLP struct {
	Sizes       []int32      `protobuf:"varint,1,rep,packed,name=sizes" json:"sizes,omitempty"`
	Activations []Activation `protobuf:"varint,2,rep,packed,name=activations,enum=evolution.mlp.Activation" json:"activations,omitempty"`
	Weights     []float64    `protobuf:"fixed64,3,rep,packed,name=weights" json:"weights,omitempty"`
}

func (m *MLP) Reset()                    { *m = MLP{} }
func (m *MLP) String() string            { return proto.CompactTextString(m) }
func (*MLP) ProtoMessage()               {}
func (*MLP) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MLP) GetSizes() []int32 {
	if m != nil {
		return m.Sizes
	}
	return nil
}

func (m *MLP) GetActivations() []Activation {
	if m != nil {
		return m.Activations
	}
	return nil
}

func (m *MLP) GetWeights() []float64 {
	if m != nil {
		return m.Weights
	}
	return nil
}

func init() {
	proto.RegisterType((*MLP)(nil), "evolution.mlp.MLP")
	proto.RegisterEnum("evolution.mlp.Activation", Activation_name, Activation_value)
}

func init() { proto.RegisterFile("mlp.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 175 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0xcd, 0x29, 0xd0,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4d, 0x2d, 0xcb, 0xcf, 0x29, 0x2d, 0xc9, 0xcc, 0xcf,
	0xd3, 0xcb, 0xcd, 0x29, 0x50, 0x2a, 0xe2, 0x62, 0xf6, 0xf5, 0x09, 0x10, 0x12, 0xe1, 0x62, 0x2d,
	0xce, 0xac, 0x4a, 0x2d, 0x96, 0x60, 0x54, 0x60, 0xd6, 0x60, 0x0d, 0x82, 0x70, 0x84, 0xac, 0xb9,
	0xb8, 0x13, 0x93, 0x4b, 0x32, 0xcb, 0x12, 0x41, 0xca, 0x8b, 0x25, 0x98, 0x14, 0x98, 0x35, 0xf8,
	0x8c, 0x24, 0xf5, 0x50, 0x4c, 0xd0, 0x73, 0x84, 0xab, 0x08, 0x42, 0x56, 0x2d, 0x24, 0xc1, 0xc5,
	0x5e, 0x9e, 0x9a, 0x99, 0x9e, 0x51, 0x52, 0x2c, 0xc1, 0xac, 0xc0, 0xac, 0xc1, 0x18, 0x04, 0xe3,
	0x6a, 0xe9, 0x71, 0x71, 0x21, 0x34, 0x09, 0xf1, 0x70, 0x71, 0x78, 0xba, 0xb8, 0xfa, 0x85, 0x78,
	0x86, 0x44, 0x0a, 0x30, 0x08, 0x71, 0x70, 0xb1, 0x84, 0x38, 0xfa, 0x79, 0x08, 0x30, 0x82, 0x58,
	0x41, 0xae, 0x3e, 0xa1, 0x02, 0x4c, 0x4e, 0x2c, 0x51, 0x4c, 0x05, 0x49, 0x49, 0x6c, 0x60, 0xf7,
	0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x5e, 0x7d, 0x35, 0x4b, 0xcc, 0x00, 0x00, 0x00,
}
