// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent/mlp/proto/mlp.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	agent/mlp/proto/mlp.proto

It has these top-level messages:
	MLP
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// Activation is a valid activation function
type Activation int32

const (
	Activation_IDENTITY Activation = 0
	Activation_TANH     Activation = 1
	Activation_RELU     Activation = 2
)

var Activation_name = map[int32]string{
	0: "IDENTITY",
	1: "TANH",
	2: "RELU",
}
var Activation_value = map[string]int32{
	"IDENTITY": 0,
	"TANH":     1,
	"RELU":     2,
}

func (x Activation) String() string {
	return proto1.EnumName(Activation_name, int32(x))
}
func (Activation) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// MLP contains the weights and specification for a multi-layer perceptron.
type MLP struct {
	Sizes       []int32      `protobuf:"varint,1,rep,packed,name=sizes" json:"sizes,omitempty"`
	Activations []Activation `protobuf:"varint,2,rep,packed,name=activations,enum=evolution.mlp.Activation" json:"activations,omitempty"`
	Weights     []float64    `protobuf:"fixed64,3,rep,packed,name=weights" json:"weights,omitempty"`
}

func (m *MLP) Reset()                    { *m = MLP{} }
func (m *MLP) String() string            { return proto1.CompactTextString(m) }
func (*MLP) ProtoMessage()               {}
func (*MLP) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MLP) GetSizes() []int32 {
	if m != nil {
		return m.Sizes
	}
	return nil
}

func (m *MLP) GetActivations() []Activation {
	if m != nil {
		return m.Activations
	}
	return nil
}

func (m *MLP) GetWeights() []float64 {
	if m != nil {
		return m.Weights
	}
	return nil
}

func init() {
	proto1.RegisterType((*MLP)(nil), "evolution.mlp.MLP")
	proto1.RegisterEnum("evolution.mlp.Activation", Activation_name, Activation_value)
}

func init() { proto1.RegisterFile("agent/mlp/proto/mlp.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0x4c, 0x4c, 0x4f, 0xcd,
	0x2b, 0xd1, 0xcf, 0xcd, 0x29, 0xd0, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x07, 0xb1, 0xf4, 0xc0, 0x2c,
	0x21, 0xde, 0xd4, 0xb2, 0xfc, 0x9c, 0xd2, 0x92, 0xcc, 0xfc, 0x3c, 0xbd, 0xdc, 0x9c, 0x02, 0xa5,
	0x22, 0x2e, 0x66, 0x5f, 0x9f, 0x00, 0x21, 0x11, 0x2e, 0xd6, 0xe2, 0xcc, 0xaa, 0xd4, 0x62, 0x09,
	0x46, 0x05, 0x66, 0x0d, 0xd6, 0x20, 0x08, 0x47, 0xc8, 0x9a, 0x8b, 0x3b, 0x31, 0xb9, 0x24, 0xb3,
	0x2c, 0x11, 0xa4, 0xbc, 0x58, 0x82, 0x49, 0x81, 0x59, 0x83, 0xcf, 0x48, 0x52, 0x0f, 0xc5, 0x04,
	0x3d, 0x47, 0xb8, 0x8a, 0x20, 0x64, 0xd5, 0x42, 0x12, 0x5c, 0xec, 0xe5, 0xa9, 0x99, 0xe9, 0x19,
	0x25, 0xc5, 0x12, 0xcc, 0x0a, 0xcc, 0x1a, 0x8c, 0x41, 0x30, 0xae, 0x96, 0x1e, 0x17, 0x17, 0x42,
	0x93, 0x10, 0x0f, 0x17, 0x87, 0xa7, 0x8b, 0xab, 0x5f, 0x88, 0x67, 0x48, 0xa4, 0x00, 0x83, 0x10,
	0x07, 0x17, 0x4b, 0x88, 0xa3, 0x9f, 0x87, 0x00, 0x23, 0x88, 0x15, 0xe4, 0xea, 0x13, 0x2a, 0xc0,
	0xe4, 0xc4, 0x1e, 0xc5, 0x0a, 0x76, 0x7b, 0x12, 0x1b, 0x98, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xbf, 0x8d, 0xc4, 0x40, 0xdf, 0x00, 0x00, 0x00,
}
